BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "PRODUCTOS" (
	"idProducto"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"descripcion"	TEXT(50) NOT NULL,
	"precio"	NUMERIC DEFAULT NULL,
	"stock"	INTEGER DEFAULT NULL,
	"idCategoria"	INTEGER NOT NULL,
	"idMedida"	INTEGER NOT NULL,
	"idTipoProducto"	INTEGER NOT NULL,
	FOREIGN KEY("idCategoria") REFERENCES "CATEGORIA"("idCategoria"),
	FOREIGN KEY("idMedida") REFERENCES "MEDIDAS"("idMedida"),
	FOREIGN KEY("idTipoProducto") REFERENCES "TIPO_PRODUCTO"("idTipoProducto")
);
CREATE TABLE IF NOT EXISTS "MEDIDAS" (
	"idMedida"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"descripcion"	TEXT(50) DEFAULT NULL,
	"idTipoProducto"	INTEGER NOT NULL,
	FOREIGN KEY("idTipoProducto") REFERENCES "TIPO_PRODUCTO"("idTipoProducto")
);
CREATE TABLE IF NOT EXISTS "EMPRESA" (
	"nombre"	TEXT NOT NULL,
	"logo"	TEXT DEFAULT NULL,
	"contrasenia"	TEXT DEFAULT NULL,
	PRIMARY KEY("nombre")
);
CREATE TABLE IF NOT EXISTS "CATEGORIA" (
	"idCategoria"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"descripcion"	TEXT(50) NOT NULL,
	"idTipoProducto"	INTEGER NOT NULL,
	FOREIGN KEY("idTipoProducto") REFERENCES "TIPO_PRODUCTO"("idTipoProducto")
);
CREATE TABLE IF NOT EXISTS "TIPO_PRODUCTO" (
	"idTipoProducto"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"descripcion"	TEXT(50) DEFAULT NULL
);
INSERT INTO EMPRESA VALUES ("Nombre de la empresa", "Imagenes/logo-default.png", "admin");
COMMIT;
